id: cbee3aece9db47e1bbcd4508c30f1b80
initial_creation_type: ocr
source_metadata:
  volumes:
    02311d56c24842e3a6bc218053d2c83d:
      base_file: v096.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
