id: D67777464
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:39:24+00:00'
last_modified: '2022-05-30T04:31:56.740114+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b588:
      image_group_id: I1PD95942
      title: དམིགས་པ་བརྟག་པ།
      total_pages: 1198
      order: 97
      base_file: b588.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
